# Generated by Django 5.2.1 on 2025-05-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plesirbe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='price',
            field=models.FloatField(),
        ),
    ]
