# Generated by Django 5.2.1 on 2025-05-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plesirbe', '0002_alter_travel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
