# Generated by Django 5.2.1 on 2025-05-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plesirbe', '0003_travel_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('hour', models.IntegerField()),
                ('rating', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Travel',
        ),
    ]
